-- =====================================================================
-- 2026-08-06_offer_notes.sql
-- Notatki Mateusza do ofert (zadanie B).
--
-- DO WKLEJENIA W SUPABASE SQL EDITOR:
--   https://supabase.com/dashboard/project/gbmvooprdfqufptfggdb/sql/new
-- Z klucza anon (tego z index.html) nie da się utworzyć tabeli ani polityki,
-- więc to jedyna część, której nie zrobi skrypt.
--
-- Skrypt jest IDEMPOTENTNY — można go wklejać kilka razy bez szkody.
-- =====================================================================


-- ── DLACZEGO OSOBNA TABELA, A NIE KOLUMNA user_notes jsonb ────────────
--
-- 1. RÓWNOLEGŁA EDYCJA. Mateusz ocenia oferty z telefonu, a czasem siedzi przy
--    laptopie z otwartą tą samą ofertą. Tablica jsonb wymaga cyklu
--    przeczytaj → dopisz → zapisz CAŁOŚĆ, więc dwa urządzenia zapisujące
--    w tej samej minucie dają „last writer wins": wpis z telefonu przepada
--    BEZ ŻADNEGO KOMUNIKATU. Osobny wiersz to INSERT — dwa równoległe wpisy
--    po prostu oba się zapisują.
-- 2. USUWANIE POJEDYNCZEGO WPISU to DELETE jednego wiersza, a nie przepisanie
--    całej tablicy (czyli znów read-modify-write i to samo ryzyko).
-- 3. REALTIME działa na wierszach. Supabase wyśle zdarzenie o dopisaniu notatki,
--    więc laptop odświeży się sam.
-- 4. HISTORIA jest naturalna: wiersz = wpis, ma własne `ts`, nie trzeba
--    parsować niczego z tekstu.
--
-- ── DLACZEGO NIE KOLUMNA `notes` ──────────────────────────────────────
-- Kolumna `notes` JEST ZAJĘTA i zostanie nadpisana przy najbliższym przebiegu:
--   • property_hunter.py wpisuje tam flagi ze scrape'u („🏞 duża działka 3299 m²,
--     273 zł/m²", „jezioro TIER1 (powidzkie)", „📄 z 6. strony wyników",
--     „🏗 rok budowy 2021"),
--   • shortlist_prices.py dopina znaczniki „[cena 06.08: 448 000 → 429 000 zł
--     (-4,2%)]" i „[nieaktualne 06.08]".
-- Na 06.08.2026 treść w `notes` miało 1730 z 2141 wierszy. Notatka użytkownika
-- zniknęłaby tam po jednym nocnym tasku.


create table if not exists public.offer_notes (
  id        bigint generated by default as identity primary key,
  offer_id  text        not null references public.offers(id) on delete cascade,
  ts        timestamptz not null default now(),
  text      text        not null check (length(btrim(text)) between 1 and 4000)
);

-- Widok „notatki jednej oferty, najnowsza u góry" to jedyne zapytanie, jakie robi
-- aplikacja — indeks dokładnie pod nie.
create index if not exists offer_notes_offer_ts_idx
  on public.offer_notes (offer_id, ts desc);

-- on delete cascade: publish_supabase.py usuwa rekordy 'rej' starsze niż 2 lata.
-- Bez kaskady zostałyby notatki-sieroty wskazujące na nieistniejącą ofertę.
comment on table public.offer_notes is
  'Notatki Mateusza do ofert. NIE mieszać z offers.notes — tam pisze scraper.';


-- ── RLS ───────────────────────────────────────────────────────────────
-- Aplikacja to statyczny plik na GitHub Pages i pisze kluczem ANON (publicznym,
-- widocznym w index.html). Na tabeli `offers` polityka na UPDATE już istnieje —
-- appka od dawna robi update({status}). Tu potrzebujemy trzech operacji:
-- select (czytanie historii), insert (nowy wpis), delete (usunięcie własnego wpisu).
-- UPDATE świadomie NIEDOZWOLONY: historia ma być dopisywana i usuwana, nie
-- przepisywana — dzięki temu żaden zapis nie może nadpisać wcześniejszego.
--
-- To prywatne narzędzie jednego użytkownika, bez logowania, więc „own entry"
-- nie ma tu technicznego znaczenia — anon MOŻE usunąć każdy wpis. Świadoma decyzja:
-- alternatywą byłoby wprowadzenie logowania do aplikacji, której cała wartość
-- polega na tym, że otwiera się jednym kliknięciem z telefonu.
alter table public.offer_notes enable row level security;

drop policy if exists offer_notes_select_anon on public.offer_notes;
create policy offer_notes_select_anon on public.offer_notes
  for select to anon, authenticated using (true);

drop policy if exists offer_notes_insert_anon on public.offer_notes;
create policy offer_notes_insert_anon on public.offer_notes
  for insert to anon, authenticated with check (true);

drop policy if exists offer_notes_delete_anon on public.offer_notes;
create policy offer_notes_delete_anon on public.offer_notes
  for delete to anon, authenticated using (true);

-- Realtime — żeby notatka dopisana z telefonu pojawiła się na laptopie bez F5.
-- (Jeśli publikacja już zawiera tę tabelę, druga próba rzuca błąd — dlatego w bloku.)
do $$
begin
  alter publication supabase_realtime add table public.offer_notes;
exception
  when duplicate_object then null;
  when undefined_object then null;   -- brak publikacji supabase_realtime
end $$;


-- ── SPRAWDZENIE (uruchom po wklejeniu) ────────────────────────────────
-- Powinno zwrócić 1 wiersz i potem go usunąć. Jeśli rzuci błąd na insert,
-- polityka RLS nie weszła.
--
--   insert into public.offer_notes (offer_id, text)
--   select id, 'test migracji — do usunięcia' from public.offers limit 1
--   returning *;
--
--   delete from public.offer_notes where text = 'test migracji — do usunięcia';
